feat: create IconBase component, add script to create Icon.tsx file

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -17,5 +17,34 @@
 
 . "$(dirname "$0")/_/husky.sh"
 
-npx tsc --noEmit
-npm run lint-staged
+echo "Running pre-commit hook..."
+
+# Check for changes in the Icon folder
+CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep 'IconV2/')
+
+if [ -n "$CHANGED_FILES" ]; then
+    echo "Changes detected in the Icon folder. Running icon generation script..."
+    
+    if ! npm run generate-icon; then
+        echo "Error: Icon generation script failed."
+        exit 1
+    fi
+    
+    git add src/Shared/Components/Icon/Icon.tsx
+else
+    echo "No changes in the IconsV2 folder. Skipping icon generation."
+fi
+
+# TypeScript check
+if ! npx tsc --noEmit; then
+    echo "Error: TypeScript check failed."
+    exit 1
+fi
+
+# Lint-staged
+if ! npm run lint-staged; then
+    echo "Error: Lint-staged failed."
+    exit 1
+fi
+
+echo "Pre-commit hook completed successfully."
